[package]
name = "TASKS"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
headless_chrome = "0.9" 
reqwest = { version = "0.11", features = ["blocking", "json"] } 
scraper = "0.12"
regex = "1"
select = "0.5.0"
